### PR TITLE
feat: utop completion and simple frontend

### PR DESCRIPTION
**Pull request by thangngoc89**
Demo: sketch-v2.surge.sh

### CODE REVIEW

**Comment by thangngoc89** [comment]
cc @bryphe any ideas why Windows build is failing?
https://dev.azure.com/hi0906/Sketch/_build/results?buildId=15&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3

**Comment by bryphe** [comment]
Hmm, trying to see if I can reproduce on my Windows machine

**Comment by bryphe** [comment]
Ah, I have seen this before. It seems to be a general bug with building JSOO on Windows - just opened an issue: https://github.com/ocsigen/js_of_ocaml/issues/788

I have a fork where I fixed that, plus a few other blockers for the Revery playground - I verified building with that fork using these resolutions works:
```
    "@opam/js_of_ocaml": "github:revery-ui/js_of_ocaml:js_of_ocaml.opam#e09793f",
    "@opam/js_of_ocaml-ppx": "github:revery-ui/js_of_ocaml:js_of_ocaml-ppx.opam#e09793f",
    "@opam/js_of_ocaml-compiler": "github:revery-ui/js_of_ocaml:js_of_ocaml-compiler.opam#e09793f",
    "@opam/js_of_ocaml-toplevel": "github:revery-ui/js_of_ocaml:js_of_ocaml-toplevel.opam#e09793f"
```

**Comment by thangngoc89** [comment]
@bryphe does your fix remove jsoo_mkcmis.exe binary? Because I'm depending on it for separate compilation.

**Comment by bryphe** [comment]
@thangngoc89 - sorry I missed this. I don't think it removes `jsoo_mkcmis`, I believe it gets installed via the `package` directive.

**Comment by thangngoc89** [comment]
@bryphe no worries. I'm working on it in #9

**Pull request merged**
